# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .links import Links
from .meta import Meta
from .task import Task


class TaskResponse(UniversalBaseModel):
    """
    Standard wrapper for single Task responses.
    """

    meta: typing.Optional[Meta] = None
    data: typing.Optional[Task] = None
    links: typing.Optional[Links] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
