# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class MetaListParams(typing_extensions.TypedDict):
    request_id: typing_extensions.NotRequired[str]
    """
    Request ID
    """

    type: typing_extensions.NotRequired[str]
    """
    Type of the primary data value in the response
    """

    limit: typing_extensions.NotRequired[int]
    """
    Number of items per page.
    """

    total: typing_extensions.NotRequired[int]
    """
    Total number of items matching the query.
    """

    page: typing_extensions.NotRequired[int]
    """
    Current page number.
    """

    pages: typing_extensions.NotRequired[int]
    """
    Total number of pages.
    """
