# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class MediaCreateResponseMetaParams(typing_extensions.TypedDict):
    request_id: typing_extensions.NotRequired[str]
    """
    Request ID
    """

    type: typing_extensions.NotRequired[str]
    """
    Type of the primary data value in the response
    """
